version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "15000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    stdin_open: true

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: uav_user
      POSTGRES_PASSWORD: uav_password
      POSTGRES_DB: uav_db
    ports:
      - "15432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

